### PR TITLE
Aarch64

### LINKED ISSUE #7: ARM Support for Folding@home - RPi support?
# Problem/Motivation

> Understand that ARM support was added a few weeks back to Folding@home.

## Expected behavior

> Does this mean we can expect an RPi compatible add-on for HA soon?

### PR DESCRIPTION
**Pull request by pssc**
# Proposed Changes

Add aarch64, Tested and built on amd64(HP Micro server Debian Linux) and Pi3(HassOS).

## Related Issues

Resolves #7 & #37

### CODE REVIEW

**Comment by frenck** [comment]
Wasn't I clear in #7 & #37?

**Comment by pssc** [comment]
I thought I would try and meet you half way and lighten the "I'm not taking the effort to add support for this." by at least doing the addon bit I can and testing.  The Pi3 is churning through work units now at ~same rate as my amd64 system.  Many hands make light work, I have done what I can, the are losts of Pi aarch64 installs out there.

**Comment by frenck** [comment]
> "I'm not taking the effort to add support for this."

Making these couple of lines of code change is not what entails supporting something.
It means maintenance in the future and also dealing with a user that is having issues. 

Running such a thing on these devices isn't recommended, having this run on e.g., a Raspberry Pi 3B+ is a very bad idea (and many more of those). Lots of people don't understand the limitations of their devices and thus leading to reported issues or even worse, hunting down performance issues on e.g. Home Assistant because the user had this add-on installed.

Hence: I'm not taking the effort to add support for this.

What do these few lines change to that?

**Comment by pssc** [comment]
Ok I understand your concerns and they are perfectly valid can we mitigate.

I agree Pi3B+'s are tight and do suffer once loaded up. I have seen this with supporting my addon's the squeezelite audio one is particularly sensitive, worse with USB sound and it all runs much better on Pi4's. Its just what I had spare the Pi4's are running HA on 32bit.

From from my aarch64 test box (Pi3B+) (vert tight):-
```
➜  ~ free -h
              total        used        free      shared  buff/cache   available
Mem:         909.7M      731.8M       41.0M      224.0K      137.0M      117.2M
Swap:        227.4M      227.3M      104.0K
```
That's just running HA with a few integrations Web Term & Folding. So are we looking at 2G memory min?

At what point do we deem a device beefy enough to run folding and ha? I can implement a check for that. Should I do the same for amd64?  an option to override that is non-trivial(not a check box)... Thinking a code from the logs unique to every install... maybe.

**Comment by frenck** [comment]
I am morw thinking about friendly declining this comtribution.

Thanks for willing to contribute.

**Pull request closed without merging**
